name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Pre-configure
      run: | 
       sudo apt update -y
       sudo apt upgrade -y
       sudo apt install wayland-protocols libuwac0-dev libwayland-dev libasound2-dev libudev-dev libxkbcommon-dev -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
